services:
  - type: web
    name: ats-score-checker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind=0.0.0.0:$PORT
    region: oregon
    plan: free
